language: node_js

node_js:
  - "node"
  - "lts/*"

script:
  - npm test -- --maxWorkers=4
  - npm start

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

service:
  - xvfb

notifications:
  email:
    on_failure: change

after_success: "npm run coveralls"

cache:
  directories:
    - node_modules
